### ISSUE TITLE
Use Rocketseat for Triton docs

### ISSUE THREAD

**Issue by diogotcorreia** [tritonmc/Triton#105]
For v3, there is a plan to opensource the docs. A redesign might be needed, so [Rocketseat](https://www.gatsbyjs.org/packages/@rocketseat/gatsby-theme-docs/) would be a great choice.

**Comment by Codixer** [comment]
I'd say [VuePress](https://vuepress.vuejs.org/) would be nicer, and easier for others to use. I've made some nice websites with it. See:
https://pinewood-builders.com/
https://pbst.pinewood-builders.com/
https://pet.pinewood-builders.com/
https://tms.pinewood-builders.com (Hidden page: https://develop.tms.pinewood-builders.com/ )
https://pia.pinewood-builders.com

**Comment by diogotcorreia** [comment]
@Codixer Seems awesome! I've seen some other sites using it as well.  
I've never used Vue before tho, I'm more of a React user. But I'll look into it anyway ;)

**Comment by diogotcorreia** [comment]
@Codixer Thanks a lot for your awesome suggestion!
I've started building the docs for Triton v3 using VuePress 😄
