### ISSUE TITLE
Issue with args got paste in chat instead of being "translated"

### ISSUE THREAD

**Issue by maxlehot1234** [tritonmc/Triton#106]
**Describe the bug**
I use a plugin (PlatinumHubCore) and I setup the message to be this:
[lang]platinumhc.flytoggled[args][arg]toggle[/arg][/args][/lang]
Triton key looks like this:
https://gist.github.com/maxlehot1234/fc59cedd6030143e162b2a480aa90587

In the chat, it looks like this:
![image](https://user-images.githubusercontent.com/5159244/84620411-eb601180-aea5-11ea-826d-d9fa45456c7b.png)
As you can see, it paste the "toggle" thing from the message

I also try to replace toggle as argument to {0} but it change nothign and it got pasted in chat.

**Server information (please complete the following information):**
 - Server Minecraft Version: [1.15.2 PaperMC build 350]
 - Client Minecraft Version (if using ViaVersion or something similar): [1.15.2]
 - Triton Version: [2.6.4]

Do I make something wrong?

Thanks again and have a nice day/night

**Comment by diogotcorreia** [comment]
Not an issue
