### ISSUE TITLE
[RFC] Suggestions for Triton v3 API methods

### ISSUE THREAD

**Issue by diogotcorreia** [tritonmc/Triton#107]
If you have an API method that you'd like to see implemented in the future, leave your comment below.

I'll start:
- Add `LanguageManager#getText`/`LanguageManager#getSign` with `Player` instead of `LanguagePlayer`.

**Comment by ZeProf2Code** [comment]
- Add `LanguageManager#getFromFormat` who can get a translated string from the `[lang]translation.key[args][arg]FirstArg[/arg][/lang]`
