### ISSUE TITLE
JSON URL Bug

### ISSUE THREAD

**Issue by ScriptixMC** [tritonmc/Triton#114]
There is a problem with JSON messages from other plugins on my server. If a JSON message contains a URL that is too long, it cannot be opened or clicked.

**To Reproduce**
Create a Test Plugin with JSON and click on the text in Minecraft:
["",{"text":"Click","color":"gold"},{"text":" "},{"text":"here","color":"dark_red","clickEvent":{"action":"open_url","value":"https://freshtimemc.de/XenForo/index.php?pages/ranks/%22%7D,%22hoverEvent%22:%7B%22action%22:%22show_text%22,%22value%22:%22Link your Account with our Website!"}},{"text":" to link your Account!","color":"gold"}]

**Expected behavior**
Please Fix the Bug

**Server information (please complete the following information):**
 - Paper Spigot 1.12.2 1618
 - ViaVersion, ViaBackwards, ViaRewards 
 - Client Version: LabyMod 1.12.2
 - BungeeCord yes WaterFall
 - 3.0.3 Triton

**Comment by diogotcorreia** [comment]
Hi!
It seems like your JSON above should be
```json
["",{"text":"Click","color":"gold"},{"text":" "},{"text":"here","color":"dark_red","clickEvent":{"action":"open_url","value":"https://freshtimemc.de/XenForo/index.php?pages/ranks/"},"hoverEvent":{"action":"show_text","value":"Link your Account with our Website!"}},{"text":" to link your Account!","color":"gold"}]
```
instead.

Anyway, Triton was indeed blocking that URL because of the slashes (`/`) after the query character (`?`). I've updated the URL regex and it works correctly now.
Fixed in v3.1.0 😄
