### ISSUE TITLE
Translation with lang tag in BTLP stopped working after BTLP update

### ISSUE THREAD

**Issue by XMadFoX** [tritonmc/Triton#115]
**Describe the bug**
After updating to the new version of BTLP (3.3.4), translation with [lang] stopped working. It was working on 3.0.9

**To Reproduce**
Set some text in plugins/BungeeTabListPlus/tabLists/default.json to [lang]Smth[/lang] and you'll see it's not working

**Expected behavior**
Translate

**Server information**
 - Server Minecraft Version: Waterfall #370
 - Client Minecraft Version any
 - Triton Version: 2.6.4 & 3.0.3

Plugin page on spigotmc https://www.spigotmc.org/resources/bungeetablistplus.313/
Source code https://github.com/CodeCrafter47/BungeeTabListPlus/

**Comment by diogotcorreia** [comment]
As with scoreboards, this is kind of a buggy thing to implement. I'll do my best to try to fix this, but keep in mind that you can also use PlaceholderAPI as [an alternative](https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PlaceholderAPI).

**Comment by diogotcorreia** [comment]
Anyway, this has been fixed in v3.1.0
