### ISSUE TITLE
HikariCP warning on startup

### ISSUE THREAD

**Issue by diogotcorreia** [tritonmc/Triton#117]
**Describe the bug**
Since HikariCP was introduced in v3.0.0, a warning message has been logged to the console on startup.
![image](https://user-images.githubusercontent.com/7467891/92614798-5b6b1180-f2b4-11ea-99be-a00140355301.png)

**To Reproduce**
Startup Spigot or BungeeCord with Triton v3+ installed

**Expected behavior**

**Server information (please complete the following information):**
 - Server Minecraft Version: any
 - Client Minecraft Version (if using ViaVersion or something similar): any
 - BungeeCord (specify if it's a fork): any
 - Triton Version: v3.1.0

**Additional context**
There's currently no way of disabling this warning from the server owner side.

**Comment by TheCoolOne123** [comment]
To fix this error, you'd need the SLF4J API, this is used to log certain aspects of your MySQL debugging info.
```xml
<!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-api -->
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>2.0.0-alpha1</version>
</dependency>
```

**Comment by diogotcorreia** [comment]
Related issue: https://github.com/brettwooldridge/HikariCP/issues/1348
