### ISSUE TITLE
Triton edits unrelated chat messages that it is not supposed to touch.

### ISSUE THREAD

**Issue by StylexTV** [tritonmc/Triton#123]
**Describe the bug**
Hey, I am the creator of _[GSigns](https://songoda.com/marketplace/product/gsigns-a-unique-map-signs-plugin-for-lobbies.508)_, a plugin that allows you to put images and gifs into item frames. Recently one of my customers contacted me because he is facing a very bizarre issue. Here is the problem:
Your plugin edits chat messages of my plugin that it is not supposed to edit. It doesn't change any text but removes functionality like displaying text upon hovering over it and actions that run when the text is clicked.

**Expected behavior**
I expect your plugin to NOT edit any messages from my plugin. Considering that you charge $10 for the plugin, that is a very crappy experience.

**Screenshots**
This is how it is supposed to look. The little cyan arrow shows a text when you hover over it and executes a command on click.
![2020-11-29_13 59 50](https://user-images.githubusercontent.com/56502218/100542603-377ff200-324b-11eb-864a-a313f430eab8.png)
After enabling your plugin it neither shows the hover text nor does it do anything on click.

**Server information (please complete the following information):**
 - Server Minecraft Version: paper spigot 1.16.4
 - BungeeCord (specify if it's a fork) [yes or no]: no
 - Triton Version: 3.1.7

**Additional context**
GSigns: version 6.2

**Comment by diogotcorreia** [comment]
I was able to successfully reproduce and fix the issue.
This was a bug introduced just a few weeks ago at the v3.1.6 update.
A fix will be available in v3.1.8.

Thank you for reporting :+1:
