### ISSUE TITLE
FlameCord Support | ProxyPingEvent

### ISSUE THREAD

**Issue by MacacoLew** [tritonmc/Triton#124]
**Is your feature request related to a problem? Please describe.**
Yes, without FlameCord support in the ProxyPingEvent Triton ignore's the cancelled event and translates when not required if the event is cancelled.

**Describe the solution you'd like**
Checking if the event is cancelled

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by diogotcorreia** [comment]
I've looked at the code for Flamecord, it doesn't seem like `ProxyPingEvent` is cancellable.

Closing as invalid.
