### ISSUE TITLE
Cancelled events in BungeeCord mode

### ISSUE THREAD

**Issue by MacacoLew** [tritonmc/Triton#125]
**Describe the bug**
Triton doesn't check if the event is cancelled in some events like LoginEvent, PluginMessageEvent and ProxyPingEvent (ProxyPingEvent feature already requested)

**To Reproduce**
No exact method but: 
Use a strong bot attack with Triton bungeecord or Spam PluginMessage to Triton (I don't know how to do the ProxyPingEvent so i finish here)

**Expected behavior**
Triton checking if the event's are cancelled

**Screenshots (optional)**
None

**Server information (please complete the following information):**
 - Server Minecraft Version: 1.16.4
 - Client Minecraft Version: 1.8.8 (ViaVersion)
 - BungeeCord: FlameCord (Fork)
 - Triton Version: 3.1.8 (Latest)

**Additional context**
None

**Comment by diogotcorreia** [comment]
This check was added for `LoginEvent` and `PluginMessageEvent`.

Thank you!
