### ISSUE TITLE
About the incompatible of TrMenu and Triton

### ISSUE THREAD

**Issue by huanyingchao** [tritonmc/Triton#127]
When the server is in BC mode, if the Spiogt server has both TrMenu and Triton plugin installed, the player will have a problem opening the menu.
The problem is that when a player opens a menu and clicks anywhere in the menu (even in the blank space), the player is kicked out of the current server, and the BC console gets an error message.
This is a overview.If you have time to fix this error,pls reply this issue.I will tell you more about it.

**Comment by diogotcorreia** [comment]
Hi!

I've looked at the issue and was able to successfully reproduce it. However, it seems like it might be an issue with ProtocolLib and not Triton.

I'll have to look at it with more attention to be sure, but I doubt there's anything I can do to fix it on my side.

**Comment by diogotcorreia** [comment]
Opened an issue on ProtocolLib: https://github.com/dmulloy2/ProtocolLib/issues/1075

**Comment by diogotcorreia** [comment]
I've implemented what PlaceholderAPI's developer said and it's working fine! :)
