### ISSUE TITLE
Book translations not working with InteractiveBooks

### ISSUE THREAD

**Issue by ManuGamer96** [tritonmc/Triton#128]
**Describe the bug**
When i put a Triton placeholder on the InteractiveBook config it does nothing, displaying the placeholder instead of the transladed line.

**To Reproduce**
Download https://www.spigotmc.org/resources/interactivebooks.45604/
Config.yml: https://pastebin.com/QWYqnqNC
Airdrop.yml (The book, placed under the books folder): https://pastebin.com/yuc9ARyt

**Expected behavior**
Translating, i guess.

**Screenshots (optional)**
https://gyazo.com/50c8443eddd98b056be28ef3951a56f8

**Server information (please complete the following information):**
 - Server Minecraft Version: 1.16.4 no viaversion or viabackwards
 - Client Minecraft Version (if using ViaVersion or something similar): 1.16.4
 - BungeeCord (specify if it's a fork): yes, waterfalll
 - Triton Version: latest (3.1.8)

**Additional context**
No errors on console, everything else works fine.

**Comment by diogotcorreia** [comment]
The user had `books: false` on config.
Closing as invalid.
