### ISSUE TITLE
Add PAPI "support"

### ISSUE THREAD

**Issue by maltl00r** [tritonmc/Triton#140]
### Is your feature request related to a problem?
I am frustrated that for example I want to translate a text like: **%player_name%'s age** which returns something like **maltloor's age** and I can't do it since it is not possible with triton, I know I could do it with [arg][/arg] but in many languages the location of the variable changes leaving as an example (SPANISH) **%player_name%'s age** which returns **maltloor's age** as you can see in the example the location of %player_name% varies according to each language (%player_name% is a placeholderapi variable).

### Describe the solution you'd like
The solution I want (or I'm sure we ALL want) is that when entering a PAPI plugin variable it should return what it should and NOT the "translated" examples:

**NOW:**
- **[lang]The %player_name%'s age is %player_firstjoin:days%[/lang]** which the plugin returns **The %player_name%'s age is %javascript_custom-script% years old** or depending on the language we have.

**I/WE WANT:**
- **[lang]The %player_name%'s age is %player_firstjoin:days%[/lang]** which the plugin should return **The maltloor's age is 21 years old** or depending on the language we have.

### Describe alternatives you've considered
There is a plugin called ChatInjector that makes any placeholder "variable" return the value it should return but the problem here are the following:
- The plugin does not work correctly as it should.
- The plugin only works in certain versions.
- The plugin only works on chat and not on scoreboards, holograms, items, etc.

### Additional context
It would be nice if this "support" could be toggled in the plugin configuration so as not to have "altercations" at the moment of having certain translations...

**Comment by diogotcorreia** [comment]
This was added in https://github.com/tritonmc/Triton/releases/tag/v3.7.0
