### ISSUE TITLE
Auto-centering text in chat

### ISSUE THREAD

**Issue by DSnow64** [tritonmc/Triton#148]
I wish triton could auto-center the text in chat as some announcers do, so I can make centered announcements, a pity that it's not possible now because triton pastes its own text.

**Comment by tyuop077** [comment]
You can use placeholder instead and let your chat/announcement plugin do it

**Comment by diogotcorreia** [comment]
Hi @DSnow64!
As @tyuop077 said, the best way to do this would be to use [PlaceholderAPI](https://triton.rexcantor64.com/concepts/placeholderapi.html), so the chat announcer plugin could align the messages itself.

Triton is already a somewhat huge plugin and it's hard to maintain alone. Adding features like this is really out of the scope of the plugin, unfortunately.

I'll be closing this issue :/
