### ISSUE TITLE
gadgetmenu not working

### ISSUE THREAD

**Issue by Laxeeee** [tritonmc/Triton#151]
Hello i'm using gadgetsmenu and i have translated the button for switch gadget page and it not works with the triton placeholder.

**Comment by diogotcorreia** [comment]
Not sure if this has been fixed meanwhile or not, but I can't seem to be able to reproduce the issue, it works for me
![image](https://user-images.githubusercontent.com/7467891/154735213-35e76786-3fc9-45b2-b484-b959641bc359.png)
