### ISSUE TITLE
Multiple fallback languages

### ISSUE THREAD

**Issue by diogotcorreia** [tritonmc/Triton#166]
**Is your feature request related to a problem? Please describe.**
There might be missing translations in all languages of the server (e.g. a server might be partially translated in two languages).

**Describe the solution you'd like**
Allow setting one (or more) fallback language(s) for each language

**Describe alternatives you've considered**
Right now the only alternative is manually setting the content value to that of the other language, but that causes duplicate content and makes it harder to follow translation progress.

**Additional context**

Example:

- If lang1 is empty, use lang2
- If lang2 is empty, use lang1

**Comment by Hutch79** [comment]
Wow, that was fast!
Thanks a lot!
