### ISSUE TITLE
error bungee cord twin

### ISSUE THREAD

**Issue by vobshestve** [tritonmc/Triton#174]
**Describe the bug**
Twin bungee cord floods with errors when trying to save changes

**To Reproduce**
I make changes to twin, save and write in the game

**Expected behavior**
twin saved successfully

**Screenshots (optional)**
https://i.imgur.com/xJpuWRU.png
**Server information (please complete the following information):**
 - Server Minecraft Version: 1.8
 - Client Minecraft Version: 1.12.2
 - BungeeCord: aegis 9.3.0
 - Triton Version: 3.7.1

**Additional context**
[Add any other context about the problem here, including error logs.
If this bug is related to another plugin malfunction because of Triton, this is where you should indicate their versions.
](https://pastebin.com/sv5Fy6Sm)

**Comment by diogotcorreia** [comment]
Fixed on 9a54cee4bad32932d0910212de4e0af9fa348c88
