### ISSUE TITLE
Translation Bottled Exp - Itemname and Lore

### ISSUE THREAD

**Issue by borovniki** [tritonmc/Triton#180]
**Describe the bug**
I have issues to translate the BittledExp plugin item itemname and lore that i get when i store my exp. When i get the item in my inventory it jzst shows the triton placeholder as itemname and lore. I enabled the **allow-in-inventory** on Bungeecord and also on all spigot servers, but no luck.    OTHER TRANSLATION IS OK, JUST THE ITEMNAME AND LORE ARE COUSING PROBLEMS.

**To Reproduce**
- Plugin: BottledExp3.0.2.0
- Language file:  Locale_EN.yml
- Placeholders in the yml file:
```
Store:
  Name: '[lang]bottledexp.store.name[/lang]'
  BottleLore: '[lang]bottledexp.store.bottlelore[args][arg][exp][/arg][/args][/lang]'
  ExpLoreColor: '[lang]bottledexp.store.explorecolor[/lang]'
```

**Screenshots (optional)**
[Screenshot-1](https://cdn.discordapp.com/attachments/395566597860884480/954310525624410132/2022-03-18_10.25.53.png)
[Screenshot-2](https://media.discordapp.net/attachments/904853387063992320/954317447245213716/unknown.png?width=1373&height=675)
[Screenshot-3](https://media.discordapp.net/attachments/904853387063992320/954317701159981066/unknown.png)
[Screenshot-4](https://media.discordapp.net/attachments/904853387063992320/954317928491257926/unknown.png?width=1393&height=676)

**Server information (please complete the following information):**
 - Server Minecraft Version: 1.17.1 - 1.18.2
 - Client Minecraft Version (if using ViaVersion or something similar): 1.18.2
 - BungeeCord (specify if it's a fork)  YES
 - Triton Version: Triton-v3.7.2

**Comment by diogotcorreia** [comment]
I cannot reproduce this issue, it works correctly for me.
![image](https://user-images.githubusercontent.com/7467891/179420220-8a66a365-dc65-4035-aedf-409200ab1ac8.png)

I've tested with Triton v3.7.2, server and client 1.18.2, BottledExp 3.0.2.0, CMILib 1.2.1.2.
It also works with the latest versions of all of the above, at the time of writing.

Please comment below or send a message on Discord if the issue persists
