### ISSUE TITLE
API breaks when used on Velocity

### ISSUE THREAD

**Issue by Esmaay** [tritonmc/Triton#183]
**Describe the bug**
When you use the API to get a message on Velocity, it'll give you a ClassNotFoundException (net.md_5.bungee.api.ChatColor)

**To Reproduce**
Install the plugin on velocity, create a velocity plugin that uses the api.

**Expected behavior**
It should return the message.

**Screenshots (optional)**
[If applicable, add screenshots to help explain your problem.](https://pastie.io/fzmlxv.properties)

**Server information (please complete the following information):**
 - Server Minecraft Version: [e.g. 1.8, 1.12, 1.14, etc...] Velocity 3.1.1
 - Client Minecraft Version (if using ViaVersion or something similar): [e.g. 1.8, 1.12, 1.14, etc...] 1.16.5
 - BungeeCord (specify if it's a fork) [yes or no] Velocity, not really a fork but its own thing
 - Triton Version: [e.g. 2.2.1, etc...] 3.7.2

**Additional context**
Add any other context about the problem here, including error logs.
If this bug is related to another plugin malfunction because of Triton, this is where you should indicate their versions.

**Comment by diogotcorreia** [comment]
This has been fixed by #230

Will be released on Triton 4.0.0, with the first beta being released today on Discord
