### ISSUE TITLE
3.8.1 book broken

### ISSUE THREAD

**Issue by OverBrave** [tritonmc/Triton#213]
### Describe the bug

![image](https://user-images.githubusercontent.com/47111280/181880390-a1dc4344-3e3b-45b6-b553-deb5054acd09.png)

### How can the bug be reproduced?

Try in 1.18.2 with Protocollib 4.8.0

### What's your server version?

git-Purpur-1632 (MC: 1.18.2)

### What's your proxy version?

Velocity 3.1.2-SNAPSHOT (git-e8bf6ab5-b161)

### What's the MC version of your client?

1.18.2

### What's the Triton version you're using?

3.8.1

**Comment by diogotcorreia** [comment]
Triton 3.8.1 requires ProtocolLib 5.0.0
Just tried it out and it works
