### ISSUE TITLE
Tab Completion not working

### ISSUE THREAD

**Issue by diogotcorreia** [tritonmc/Triton#216]
### Describe the bug

Some commands don't have tab completion working correctly (e.g. `triton database`)

### How can the bug be reproduced?

1. Try typing the command on chat and see that it does not auto complete

### Which Spigot fork are you using?

Vanilla Spigot (from BuildTools)

### What's your server version?

1.19.2

### Which proxy are you using?

BungeeCord

### What's your proxy version?

1.19.2

### What's the MC version of your client?

1.19.2

### What's the Triton version you're using?

3.8.1

### Additional Information

Reported by someone on Discord

**Comment by PalmTamino** [comment]
List of commands that are also not in there:

/triton help
/triton setlanguage
/triton reload (Both /triton reload "s" and "a" not in there
/triton openselector
/triton loglevel
/triton sign
/triton info
/triton getflag
