### ISSUE TITLE
Triton messages are only tranlsated in-game and not in the console 

### ISSUE THREAD

**Issue by PalmTamino** [tritonmc/Triton#218]
### Describe the bug

![grafik](https://user-images.githubusercontent.com/36358673/183604317-9994124d-b842-47bd-ade1-4756948dc991.png)

![grafik](https://user-images.githubusercontent.com/36358673/183604522-5f0aa60b-a333-4d9c-8af2-4d319014dbc9.png)

### How can the bug be reproduced?

1 Install Triton
2 Set it up correctly
3 Translate triton

4 execute /twin in-game on the server-> You will see your tranlsation applied
5 execute /twin from console -> Translations won't be applied

### Expected behaviour

Translations should be applied everywhere

### Which Spigot fork are you using?

Purpur

### What's your server version?

Current: git-Purpur-1752 (MC: 1.19.2)

### Which proxy are you using?

FlameCord

### What's your proxy version?

Flamecord 1.0.6

### What's the MC version of your client?

1.19.2

### What's the Triton version you're using?

3.8.1 (Both Proxy and Servers)

**Comment by diogotcorreia** [comment]
Already a feature:
https://github.com/tritonmc/Triton/blob/4c776742f7ccaecce1d3cb85480e16247c8f0c93/core/src/main/resources/config.yml#L246

**Comment by PalmTamino** [comment]
My mistake... did not enable translation of terminal in config -> https://github.com/tritonmc/Triton/blob/4c776742f7ccaecce1d3cb85480e16247c8f0c93/core/src/main/resources/config.yml#L246
