### ISSUE TITLE
RGB colors in inventory title are not working

### ISSUE THREAD

**Issue by TheXplore** [tritonmc/Triton#225]
### Describe the bug

Using RGB colors in inventory names results in the wrong color being shown.

### How can the bug be reproduced?

1. Install Triton
2. Open inventory with title which contains a custom RGB color
`player.openInventory(Bukkit.createInventory(player, 3 * 9, ChatColor.of("#0cf246") + "Test"));`
3. Color of the inventory title is gold (probably because #0cf246 ends in 6)

### Expected behaviour

Inventory title should be green (#0cf246) and not gold.

### Which Spigot fork are you using?

PaperMC

### What's your server version?

git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)

### Which proxy are you using?

BungeeCord

### What's your proxy version?

git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:5cdba87:1659

### What's the MC version of your client?

1.18

### What's the Triton version you're using?

3.8.1

**Comment by TheXplore** [comment]
![image](https://user-images.githubusercontent.com/26611093/186007540-4adfb00f-2e88-49e1-96f7-93bc03fd531d.png)

**Comment by diogotcorreia** [comment]
Thanks!
I'm pretty sure I know what it is, I'll fix it ASAP

**Comment by TheXplore** [comment]
Perfect, thanks! I just created another bug report regarding key components ;)

**Comment by diogotcorreia** [comment]
This was somehow not on the Project I was tracking for the issues on 3.8.2, so I forgot to fix it :/
I'll be releasing 3.8.3 soon to address this

**Comment by TheXplore** [comment]
The build you provided on discord does seem to work properly
![image](https://user-images.githubusercontent.com/26611093/190973011-57db7797-ef09-4db2-a721-90fa1b6485a5.png)
