### ISSUE TITLE
Minimessage key components not working in chat (e.g. <key:key.hotbar.1>)

### ISSUE THREAD

**Issue by TheXplore** [tritonmc/Triton#226]
### Describe the bug

Key components sent via MiniMessage fail to be sent correctly.

![image](https://user-images.githubusercontent.com/26611093/186008873-44ceacf8-1356-47cd-a641-f6d74580699e.png)

### How can the bug be reproduced?

1. Install Triton
2. Send minimessage to player which contains key komponent like "\<key:key.hotbar.1\>) Verreisen"
3. Only ") Verreisen" gets sent to player

### Expected behaviour

"1) Verreisen" should be shown instead of ") Verreisen"

### Which Spigot fork are you using?

PaperMC

### What's your server version?

git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)

### Which proxy are you using?

BungeeCord

### What's your proxy version?

git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:5cdba87:1659

### What's the MC version of your client?

1.18

### What's the Triton version you're using?

3.8.1

**Comment by TheXplore** [comment]
Is there an estimate on when this might be fixed? 
It's currently preventing us from using triton on our production network...

**Comment by diogotcorreia** [comment]
This is fixed in the v4 beta and backporting the fix would be counter productive.
I'll work on making v4 work correctly on Spigot and Bungee!

**Comment by TheXplore** [comment]
I wrote a small fix for this issue in our fork, so thats fine with me

**Comment by TheXplore** [comment]
com.rexcantor64.triton.language.parser.AdvancedComponent:

Line 97 (fromBaseComponent):
`if (!onlyText && comp instanceof KeybindComponent) {
            	KeybindComponent kc = (KeybindComponent) comp;
                builder.append("\uE700")
                        .append(kc.getKeybind())
                        .append("\uE700");
            }`

Line 240 (toBaseComponent): 
`} else if (c == '\uE700') {
            	 i++;

            	 StringBuilder key = new StringBuilder();
                 while (text.charAt(i) != '\uE700') {
                     key.append(text.charAt(i));
                     i++;
                 }

                 if (builder.length() != 0) {
                     component.setText(builder.toString());
                     builder = new StringBuilder();
                     BaseComponent previousComponent = component;
                     list.add(component);
                     component = new TextComponent("");
                     ComponentUtils.copyFormatting(previousComponent, component);
                 }

                 KeybindComponent kc = new KeybindComponent(key.toString());
                 ComponentUtils.copyFormatting(component, kc);
                 list.add(kc);
            }`
