### ISSUE TITLE
Scoreboard becomes invisible when use async-protocollib

### ISSUE THREAD

**Issue by myavuzokumus** [tritonmc/Triton#251]
### Describe the bug

When turn on async-protocollib in config, scoreboard becomes invisible.

### Which Spigot fork are you using?

Other (specify below)

### What's your server version?

Current: git-petal-"3efc156" (MC: 1.19.2)* Previous: git-petal-"cc713c0" (MC: 1.19.2)

### Which proxy are you using?

Velocity

### What's the MC version of your client?

1.19.2

### What's the Triton version you're using?

4.0.0-Snapshot

**Comment by DarkyCat** [comment]
What version of ProtocolLib is on your server and what ScoreBoard plugin are you using?

**Comment by OverBrave** [comment]
Protocollib 5.0, TAB 3.1.5

**Comment by diogotcorreia** [comment]
Related to #299 and #296 (v3)
