### ISSUE TITLE
Armorstand is not translated

### ISSUE THREAD

**Issue by iCrashMix0** [tritonmc/Triton#258]
### Describe the bug

Armorstand is not translated.

### How can the bug be reproduced?

1. you need the following plugins: (Latest - 4.4.4) https://www.spigotmc.org/resources/armor-stand-tools.2237/ & (Latest - 3.8.2) https://www.spigotmc.org/resources/triton-translate-your-server.30331/

2. a Paper-1.19.2 Minecraft server

3. join the server & watch the video (short): https://youtu.be/R-1ogzVMqdc

4. end of the tutorial

### Which Spigot fork are you using?

PaperMC

### What's your server version?

This server is running Paper version git-Paper-260 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 2b47227) You are 11 version(s) behind Download the new version at: https://papermc.io/downloads

### Which proxy are you using?

I'm not using a proxy

### What's the MC version of your client?

1.19.2

### What's the Triton version you're using?

3.8.2

**Comment by diogotcorreia** [comment]
I was able to reproduce this, will investigate.

**Comment by diogotcorreia** [comment]
After investigating I noticed that I had changed the language tags for entities on my server (to `[l]`).
Then I confirmed that this works correctly on my server, so I can't reproduce your issue.
