### ISSUE TITLE
Sign is not recognized on 1.19.2 Paper Server

### ISSUE THREAD

**Issue by iCrashMix0** [tritonmc/Triton#259]
### Describe the bug

Shield is not recognized on 1.19.2 Paper Server.

### How can the bug be reproduced?

1. you need the following plugins: (Latest - 3.8.2) https://www.spigotmc.org/resources/triton-translate-your-server.30331/

2. a Paper-1.19.2 Minecraft server

3. join the server

4. planing sign on the wall (I took an oak sign)

5. and type "/triton sign set" and it will directly say that the sign was not found.

6. end of the tutorial

### Which Spigot fork are you using?

PaperMC

### What's your server version?

This server is running Paper version git-Paper-260 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 2b47227) You are 11 version(s) behind Download the new version at: https://papermc.io/downloads

### Which proxy are you using?

I'm not using a proxy

### What's the MC version of your client?

1.19.2

### What's the Triton version you're using?

3.8.2

**Comment by diogotcorreia** [comment]
I can't reproduce this, I've used Paper 1.19.2 (build 282) and I can use the command.
Keep in mind that `/triton sign set` requires an argument, `/triton sign set <sign group id>`.
