### ISSUE TITLE
Possible Incompatibility with Happy Hud Plugin

### ISSUE THREAD

**Issue by DeonHarwnart** [tritonmc/Triton#279]
### Describe the bug

After testing, when installing Happy Hud and Triton together. I notice that when a player join, the server start freezing and then crashed.

Mention server log before stop running: https://pastebin.com/5ahYbGud

### How can the bug be reproduced?

Install Triton with Happy Hud

Happy Hud: https://www.spigotmc.org/resources/%E2%AD%90happyhud%E2%AD%90custom-bars-and-number-displays%E2%9C%85replace-vanilla-look%E2%9C%85auto-resource-pack-builder.96299/

### Expected behaviour

The server should run these two plugins without any error

### Which Spigot fork are you using?

Paper Latest

### What's your server version?

1.19.3

### Which proxy are you using?

Bungeecord Latest

### What's your proxy version?

Latest

### What's the MC version of your client?

1.19.3

### What's the Triton version you're using?

Latest

### Additional Information

I also post this error on their github issue page: https://github.com/Ehhthan/HappyHud-Issues/issues/39

**Comment by diogotcorreia** [comment]
Hi!
I think I'm going to need more information. Could you DM me on Discord? `DiogoCorreia#7295`

**Comment by Ehhthan** [comment]
This is solved by just disabling the action bar in the triton config. Not worth it to add full compatibility due to how HappyHud generates text.

**Comment by diogotcorreia** [comment]
Nice to know.
Triton v4 fixes this as well since it doesn't touch text without placeholders anymore.
Will close this.
