### ISSUE TITLE
can't find translation

### ISSUE THREAD

**Issue by DarkCoder15** [tritonmc/Triton#286]
### Describe the bug

I added translation, key, and set up placeholders. But it says that message not found.

### How can the bug be reproduced?

1. Install triton
2. Create translation
3. set placeholders in another plugin
4. Message not found

### Expected behaviour

The message should translate

### Which Spigot fork are you using?

PaperMC

### What's your server version?

git-Paper-81 (MC: 1.19)

### Which proxy are you using?

I'm not using a proxy

### What's the MC version of your client?

1.19

### What's the Triton version you're using?

3.8.3

**Comment by diogotcorreia** [comment]
Hi!
This is most likely a configuration issue and not a bug.
You have not given enough information for me to diagnose the issue.

Please reach out on [Triton's Discord](https://triton.rexcantor64.com/discord) for support.
