### ISSUE TITLE
actionbar is always white when using 1.8 clients

### ISSUE THREAD

**Issue by FallenCrystal** [tritonmc/Triton#297]
### Describe the bug

actionBar is not colorized correctly on 1.8 clients.

### How can the bug be reproduced?

install plugin.

```
public String ca(String text) {return ChatColor.translateAlternateColorCodes('&', text);}
public void actionbar(ProxiedPlayer p, String msg) {p.sendMessage(ChatMessageType.ACTION_BAR, new TextComponent(ca(message)));}
```
and then. send an actionbar message to the 1.8 client.
```
actionbar(tester, "&aa&bb&cc&dd&ee");
```
u can get white string "abcde"

### Expected behaviour

correct coloring

### Which Spigot fork are you using?

PaperMC

### What's your server version?

git-PaperSpigot-f6fba00-99355adc (MC:1.8.8) 

### Which proxy are you using?

Other (specify below)

### What's your proxy version?

NullCordX - 3.7.4

### What's the MC version of your client?

1.8

### What's the Triton version you're using?

3.8.3, 3.6.0(test)

### Additional Information

whether its nullcordx, flamecord, waterfall, or native bungeecord. all have this error (at least when i tested it)
only on 1.8 clients. 1.9+ clients work fine.

**Comment by diogotcorreia** [comment]
Was it working on 3.6.0?
I'm pretty sure this worked before, so it must be a regression.

**Comment by FallenCrystal** [comment]
> Was it working on 3.6.0? I'm pretty sure this worked before, so it must be a regression.

nope

**Comment by FallenCrystal** [comment]
btw only on bungeecord. actionbar sender target is proxiedplayer

**Comment by diogotcorreia** [comment]
Oh... that makes sense, did not noticed that.
I think that never worked then, I'll take a look.

However, does it work if you create the BaseComponent correctly?

```java
public String ca(String text) {return ChatColor.translateAlternateColorCodes('&', text);}
public void actionbar(ProxiedPlayer p, String msg) {p.sendMessage(ChatMessageType.ACTION_BAR, TextComponent.fromLegacyText(ca(message)));}
```

(Notice the change from `new TextComponent(...)` to `TextComponent.fromLegacyText(...)`)

Also, does it work if Triton isn't installed on the proxy?

**Comment by FallenCrystal** [comment]
> Also, does it work if Triton isn't installed on the proxy?

yes


> (Notice the change from to new TextComponent(...)TextComponent.fromLegacyText(...))

i will test later

**Comment by FallenCrystal** [comment]
> (Notice the change from to new TextComponent(...)TextComponent.fromLegacyText(...))

still

![image](https://user-images.githubusercontent.com/71176602/232301499-b923781c-ba36-482e-90ac-d3a4d7154ddf.png)
