### ISSUE TITLE
Random UUID by LibreLogin are not used on Bungeecord.

### ISSUE THREAD

**Issue by mrpf-me** [tritonmc/Triton#320]
### Describe the bug

I always get the "default" translation for bungee commands.
Also selecting with /lang does not work for bungee.

I use [LibreLogin](https://github.com/kyngs/LibreLogin) UUID generation to ensure a smooth workflow between premium and cracked players.

For this purpose LibreLogin (Auth plugin) **generates a random UUID once when joining the network** for the first time and passes it to all Spigot subservers. This is also used by Minecraft in the world/playerdata folder.

However, **Triton does not pick the random UUID, instead it picks the cracked UUID** of the player's name. 
I have had this problem only with Triton, with bungee plugins like [Plan](https://github.com/plan-player-analytics/Plan) or [LiteBans](https://gitlab.com/ruany/LiteBans) there were no difficulties using the random UUID system.

### How can the bug be reproduced?

1. install Triton with the help of the installation guide
2. database / network setup configured
3. joining the Bungee network
4. bungee cord command used
5. wrong language is displayed

### Expected behaviour

That Triton, like all other BungeeCord plugins, picks up the random UUID and uses it in the database for my player settings. 

### Which Spigot fork are you using?

PaperMC

### What's your server version?

git-Paper-55 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: e4b40dd)

### Which proxy are you using?

Waterfall

### What's your proxy version?

git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536 by md_5

### What's the MC version of your client?

1.20.1

### What's the Triton version you're using?

3.9.0

### Additional Information

If you need further information, please do not hesitate to contact me.

**Comment by diogotcorreia** [comment]
Multiple people have reported this same issue, therefore I'm reopening it.
