### ISSUE TITLE
Problems with TownyChat

### ISSUE THREAD

**Issue by Sebasorova** [tritonmc/Triton#350]
### Describe the bug

When using TownyChat to format the chat, the text is not being translated and instead it appears unformatted (like [lang][/lang])

![image](https://github.com/tritonmc/Triton/assets/56850980/e0b0fe5e-1e3e-4e0f-b469-698d052b0ed8)

### How can the bug be reproduced?

1. Install plugin TownyChat from Towny
2. Use the config for the default channel of the plugin: `default: '{permgroupprefix} {nationformatted}{modplayername}: {msg}'`
3. Start the server and use the chat

### Expected behaviour

Instead of TownyChat showing the message that Triton translates (using packages i imagine) it shows the [lang][/lang] message even without chat encryption.

### Which Spigot fork are you using?

Purpur

### What's your server version?

git-Purpur-1985 (MC: 1.19.4)

### Which proxy are you using?

Waterfall

### What's your proxy version?

git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545

### What's the MC version of your client?

1.19.4

### What's the Triton version you're using?

3.9.1

### Additional Information

The plugin works correctly on the TAB and the scoreboard, but not on TownyChat

**Comment by diogotcorreia** [comment]
I've successfully reproduced and fixed the issue, but I am still testing it across versions and fixing some bugs (i.e. it is not working in 1.19.2 at the moment, but it works on 1.19.4) :partying_face:

**Comment by diogotcorreia** [comment]
This will be fixed in 3.9.2, but you'll need to enable the new option on config:
https://github.com/tritonmc/Triton/blob/1d7afbd0df117d4eeaae5f9c258733eba6b8fb32/core/src/main/resources/config.yml#L142
