### ISSUE TITLE
Motd issue on v4

### ISSUE THREAD

**Issue by mario414x** [tritonmc/Triton#371]
### Describe the bug

Hello! This error spams my proxy console using triton in my motd: https://mclo.gs/wJG4mzL
I use AdvancedNMotd as my motd plugin. We have discussed before on discord about it

### Which Spigot fork are you using?

Other (specify below)

### What's your server version?

just a limbo server

### Which proxy are you using?

Waterfall

### What's your proxy version?

waterfall-1.20-559

### What's the MC version of your client?

1.18.2

### What's the Triton version you're using?

4.0.0

**Comment by diogotcorreia** [comment]
I can reproduce this on both Waterfall and BungeeCord
