### ISSUE TITLE
[v4] Don't know how to turn into a Component

### ISSUE THREAD

**Issue by HappyAreaBean** [tritonmc/Triton#374]
### Describe the bug

* When a player joins, it throws errors to console: https://paste.happyareabean.cc/hmBHpBl4Cb74hJt
* %triton placeholder is not functional in holograms
  * ![image](https://image.happyareabean.cc/u/wnDctIxQQFJYjuXw.png)
* Item's translation is not working properly.
  * ![image](https://image.happyareabean.cc/u/PvIcDcare8nA16r6.png)

### Which Spigot fork are you using?

Other (specify below)

### What's your server version?

ImanitySpigot3 - 1.8.8

### Which proxy are you using?

Velocity

### What's your proxy version?

3.3.0-SNAPSHOT (git-00ef92bc-b312)

### What's the MC version of your client?

1.20.4

### What's the Triton version you're using?

4.0.0-SNAPSHOT

### Additional Information

As an FYI, when I install it on a fresh setup, it would say: `java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component` https://paste.happyareabean.cc/bVKGSR7lcsw6a6h

The first time I installed on my production server, I didn't notice this error at first, but then I found out it was one of the plugins that shipped adventure-API without shading, so that's why it did not complain about missing adventure.

Btw, this is my plugins list (in `platformDump.plugins`): https://dump.viaversion.com/a43d220f1994ca02763d5ceff146c168900e9e5019656f49a02f6b02ddb61727

**Comment by diogotcorreia** [comment]
Oh, since adventure is not available, it is expected that v4 does not work.
There is currently a build for BungeeCord on Discord (it works on Spigot servers without adventure); could you try it?

There is currently work being done on #285 that will fix this issue!

**Comment by diogotcorreia** [comment]
Latest builds of v4 should now work with this (ProtocolLib seems to be requiring Java 9+ tho)
