### ISSUE TITLE
Placeholder is not updated correctly in some situations in the inventory

### ISSUE THREAD

**Issue by AxDevv** [tritonmc/Triton#387]
### Describe the bug

Placeholder is not updated correctly

### How can the bug be reproduced?

I put myself on survival then I give myself 2 items and I go into my inventory, then I slide an item without dropping it,and then right click on the other item to move it in the inventory, and when i drop the first item in my inventory shows the [lang]...

### Which Spigot fork are you using?

PaperMC

### What's your server version?

git-Paper-196 (MC: 1.20.1)

### Which proxy are you using?

Velocity

### What's your proxy version?

velocity 3.3.0

### What's the MC version of your client?

1.20.4

### What's the Triton version you're using?

4.0.0-SNAPSHOT

### Additional Information

https://www.youtube.com/watch?v=FfMG9MTywQQ

**Comment by exzolink** [comment]
If double click item in any inventory it will lose packet name

**Comment by diogotcorreia** [comment]
I've managed to reproduce this issue. It appears to be present on MC 1.17 and above.
