### ISSUE TITLE
CMI GUI

### ISSUE THREAD

**Issue by TomHo41** [tritonmc/Triton#389]
### Describe the bug

I used generator tool for CMI. When I open any GUI made by CMI it only shows placeholder not result of it.
![2024-03-01_20 18 53](https://github.com/tritonmc/Triton/assets/126081863/d5b5f208-f0c1-423d-a0f9-c23ad8d82ab6)

### How can the bug be reproduced?

Used generator tool
Done all things for generator
Executed /cmi ender
It showed only placeholder not result as name of GUI

### Expected behaviour

Should set correct name of GUI

### Which Spigot fork are you using?

PaperMC

### What's your server version?

Paper version git-Paper-167 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 0c0a480)

### Which proxy are you using?

I'm not using a proxy

### What's the MC version of your client?

1.18.2

### What's the Triton version you're using?

3.9.5

### Additional Information

CMI 9.6.10.7
CMI lib 1.4.5.2

**Comment by diogotcorreia** [comment]
Unfortunately this is likely a limitation in CMI and/or Minecraft: there is a limit to the length of the title of the GUI. For Triton to work, it has to be able to read the entire placeholder.

I'd recommend making the key of the placeholder smaller.

**Comment by TomHo41** [comment]
I renamed placeholder from cmi.command.ender.info.title to cmi.ender and it works. So thanks. I looked it bit deeper I think it's limitation of CMI. Tried it to make GUI with Skript and it works with the old placeholder. So my question is Should I report it to as bug to the tool or let it be?

**Comment by diogotcorreia** [comment]
@TomHo41 I think the limitation is in place on purpose — older clients might crash if they receive a title that's over the limit.
But you can ask them and see if it is possible.
