### ISSUE TITLE
The villagers' trading price changes are not displayed properly.

### ISSUE THREAD

**Issue by FallenCrystal** [tritonmc/Triton#421]
### Describe the bug

The price change of items traded by villagers is not displayed. Unless set `language-creation.items.enabled` to false or disable triton.
It is still possible to trade with the price of changed. But it looks very strange in the client. 

### How can the bug be reproduced?

1. Install Triton and start the 1.21 minecraft server
2. Give a `Hero of the village` effect or make the villagers increase their prices.
3. Open the trading window. The price change does not show properly after the Triton installation.

### Expected behaviour

It should also be display correctly with triton installed.

### Which Spigot fork are you using?

Other (specify below)

### What's your server version?

Leaf version 1.21-DEV-ver/1.21@b2692f7 (2024-07-04T18:35:11Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Which proxy are you using?

I'm not using a proxy

### What's the MC version of your client?

1.21

### What's the Triton version you're using?

3.10.1 @ 07d2cf1

### Additional Information

Before using triton:

![image](https://github.com/tritonmc/Triton/assets/71176602/527ba38c-4a7b-435b-9cca-c1fea76fd228)

Using triton:

![image](https://github.com/tritonmc/Triton/assets/71176602/69bff157-fa5d-4428-8f19-028c15df5580)

**Comment by diogotcorreia** [comment]
I confirm that I'm able to reproduce this issue and I'll take a look

**Comment by diogotcorreia** [comment]
This has been fixed on v4. I'll backport it to v3 tomorrow.
Thanks for reporting this!
