### ISSUE TITLE
Automatic language detection does not work on Velocity

### ISSUE THREAD

**Issue by Fe1son** [tritonmc/Triton#446]
### Describe the bug

On the spigot server (without a proxy) it works for me, but in conjunction with Velocity it does not work, only when I select a language on the spigot server I get messages from Velocity about automatic language selection, and then messages about language selection, in general, either I configured something incorrectly, or...

But when I have already chosen the language myself, it is saved on all proxies and changes on servers (there is no problem here), but there is a problem with the first automatic detect
I also think that it is because of the local server, because only 127.0.0.1 is created on Velocity, and if it is automatically detected on a Spigot server without a proxy, both 127.0.0.1 and UUID are created there

Automatically with proxy:
![image](https://github.com/user-attachments/assets/940ad358-9f82-48de-bf18-9a2f8d162b42)

without proxy (detect selection worked (Ukrainian was selected), and with the proxy English is selected (the main language)
![image](https://github.com/user-attachments/assets/dd8ac5d3-1fd4-48f9-9c96-0bff54d93467)

The problem disappeared that detection occurs only when selecting a language already on the spigot server (if bungeecord false), but the language is not detected normally at velocity.

### Which Spigot fork are you using?

Other (specify below)

### What's your server version?

Current: git-Plazma-"3972882" (MC: 1.20.4)*

### Which proxy are you using?

Velocity

### What's the MC version of your client?

1.20.4

### What's the Triton version you're using?

3.9.5 (on Plazma) | 4.0.0-SNAPSHOT-all (11.09.2024) (Velocity)

**Comment by diogotcorreia** [comment]
Fixed by #457
