### ISSUE TITLE
[TWIN] Translation list overriding each other

### ISSUE THREAD

**Issue by ColaIan** [tritonmc/Triton#79]
https://cdn.discordapp.com/attachments/681139496405696574/681152521028239496/Screenshot_2020-02-23_at_10.56.51_PM.png

**Comment by TheCoolOne123** [comment]
![img](https://cdn.discordapp.com/attachments/681139496405696574/681152521028239496/Screenshot_2020-02-23_at_10.56.51_PM.png)

**Comment by diogotcorreia** [comment]
Another report from a user:


> If in the web, we setup no collection and save, triton will put these keys into a new default creation created automatically.
> If we ./twin again and edit these keys to a specific collection, save it and enter the command in the chat/console.
> 
> After that, if we ./twin again, we got this issue in keys, they are one on the other and these keys are put in the default collection and the new one assigned manually in the web interface:
> ![image](https://user-images.githubusercontent.com/7467891/85603820-a166f080-b648-11ea-8f78-6fd54d9e05ad.png)

**Comment by diogotcorreia** [comment]
Should be fixed in TWIN v3.0.0-beta.1
