### ISSUE TITLE
TWIN access improvement

### ISSUE THREAD

**Issue by XMadFoX** [tritonmc/Triton#85]
**Idea**
Ability to generate twin with access only to the specified collection and language

**Describe the solution you'd like**
/twin CollectionName LangName

**Comment by diogotcorreia** [comment]
Thanks for your suggestion, it will be available on Triton v3.1.0!

The syntax will be `/twin upload [collection name] [lang name]`.  
You can have multiple collections/languages, separated by `:` (this character can't be in file names, so it's perfect).
You can also use `*` to include all collections or languages. This is especially useful if you want to filter languages but keep all collections.
