### ISSUE TITLE
%triton_lang% and %triton_lang_PLAYERNAME% placeholders

### ISSUE THREAD

**Issue by tyuop077** [tritonmc/Triton#89]
**Is your feature request related to a problem? Please describe.**
Add server creators ability to apply specific command when GUI/Shop opened (or warped/used specific command) using placeholder's check server-side using %triton_lang% issued by Playername or %triton_lang_PLAYERNAME% issued by server (Playername should be online) to make (example) bedwars games for English players and specific-language players. Add ability to make commands to check player's current lang.

**Comment by tyuop077** [comment]
Ex. Commands using PAPI's JavaScript

**Comment by diogotcorreia** [comment]
I'm pretty sure this can already be created with Triton's current feature set.

Example:
1. Create a translation with the key `lang`.
2. Fill the text in each language with the language code. (e.g. for English, put `en`; for Portuguese put `pt`; etc)
3. `%triton_lang%` now returns `en` or `pt` (or whatever you put in the translation)
4. You can tell PAPI to fetch the placeholder as whatever player you want to check the language. (In Java, use `PlaceholderAPI.setPlaceholder(player, "%triton_lang%")`, in PAPI JavaScript `PlaceholderAPI.static.setPlaceholder(player, "%triton_lang%")`

If there is any use case I haven't covered here, please DM me on Discord.
