### ISSUE TITLE
Saving yml should be async

### ISSUE THREAD

**Issue by Shadow192** [tritonmc/Triton#98]
**Describe the bug**
Saving the players.yml should be done async to reduce the lag caused by that.

**Screenshots (optional)**
https://sfy.cx/sd/u/102127.png

**Server information (please complete the following information):**
 - Server Minecraft Version: 1.8.8
 - Client Minecraft Version (if using ViaVersion or something similar): 1.12.2
 - BungeeCord (specify if it's a fork) Waterfall
 - Triton Version: 2.6.3 ( latest )

**Comment by diogotcorreia** [comment]
This now happens in `Triton v3.0.0-beta.1`.
If you wish to be part of the beta, please DM me on Discord.
